apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  labels:
    homelab/stack: immich
spec:
  project: default
  source:
    repoURL: ${GITHUB_REPO}
    targetRevision: main
    path: k8s/stacks/immich
    plugin:
      name: kustomize-envsubst
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
