apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# List every Application CRD file here.
# Adding a new app = add the file + one line here, then git push.
resources:
  - argocd-ingress.yaml
  - auth.yaml
  - backup.yaml
  - cloud.yaml
  - db.yaml
  - immich.yaml
  - whoami.yaml
  - infra-pdbs.yaml
  - infra-ingress-nginx.yaml
  - infra-longhorn.yaml
  - infra-longhorn-config.yaml
  - infra-monitor.yaml
  - infra-monitor-config.yaml
